name: Update Wakatime Stats
on:
  schedule:
    # Runs every day at 12:00am (UTC)
    - cron: '0 0 * * *'
jobs:
  update-readme:
    name: Update Readme with Wakatime Stats
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wakatime
    - name: Update README with Wakatime Stats
      env:
        WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python update_readme.py
